backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "prices" # Used in routes, e.g., /admin/collections/blog
    label: "Prices" # Used in the UI
    folder: "src/_posts/prices" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Rows", name: "rows", widget: "markdown"}
